### ISSUE TITLE
Can't use `sync` command at hi18n/cli@v0.1.5

### ISSUE THREAD

**Issue by lightsound** [wantedly/hi18n#70]
## Why

I tried to find the cause of the error, but couldn't figure out why it wasn't working. If you know, I would like to know how to fix it.

## What

When I call the sync command, following error message is shown.

> Error: Error on pages/_app.tsx: Parsing error: No Babel config file detected for /Users/koto/ghq/github.com/lightsound/nexst-tailwind/pages/_app.tsx. Either disable config file checking with requireConfigFile: false, or configure Babel so that it can find the config files.
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/8220973/170853026-1936a4fa-5fc8-4757-9111-ce20a3f4ffec.png">

## Environment

- macOS Monterey (v12.4)
- `Node.js` v16.13.0
- `@hi18n/cli` v0.1.5
- [Dependencies](https://github.com/lightsound/nexst-tailwind/blob/2ada39053ae7b2085bb523f9356566b95eb0ff2e/package.json#L30-L74)

## FYI

[Here](https://github.com/lightsound/nexst-tailwind/pull/653/files) is the repository I was working on. I was trying to use hi18n by referring to [this article](https://us.wantedly.com/companies/wantedly/post_articles/399501).

**Comment by qnighy** [comment]
Thanks for trying our library! hi18n currently uses `@babel/eslint-parser` under the hood, and it looks for `.babelrc` or `babel.config.js` to configure the parser.

As there is no special reason to use `@babel/eslint-parser` over `@typescript-eslint/parser`, we may switch the parser to TSESLint and then you won't need a special configuration. In the meantime, however, you may want to place an appropriate config file to trick hi18n into using it.

**Comment by lightsound** [comment]
Thanks! I'm trying with `.babelrc`, but it seems to have many inconveniences to use with Next.js.

First, you can't use the SWC compiler; [Next.js will use Babel as the compiler if you have a babel config file](https://nextjs.org/docs/advanced-features/customizing-babel-config). I don't want to use Babel because SWC has better performance.

Secondly, [absolute imports](https://nextjs.org/docs/advanced-features/module-path-aliases) don't work, I put `.babelrc` and tried the `sync` command, but it doesn't recognize absolute imports. I tried to solve this with `babel-plugin-module-resolver`, but it failed.

Do you have plans to support Next.js?

**Comment by qnighy** [comment]
> Do you have plans to support Next.js?

In fact we're already using it with Next.js in our private repositories, but we still use Babel for several reasons.

**Comment by lightsound** [comment]
Oh, I asked the wrong question. 🙏

Do you have plans to support SWC compiler or absolute imports for Next.js?

**Comment by qnighy** [comment]
> Do you have plans to support SWC compiler or absolute imports for Next.js?

Ah, I should have phrased my initial response differently:

> As there is no special reason to use `@babel/eslint-parser` over `@typescript-eslint/parser`, we may switch the parser to TSESLint and then you won't need a special configuration.

In this line I meant I plan to improve hi18n so that you can choose not to use `@babel/eslint-parser`. But it may take some time. Sorry for keeping you waiting!

**Comment by lightsound** [comment]
> In this line I meant I plan to improve hi18n so that you can choose not to use @babel/eslint-parser.

Oh, I understand completely.

> Sorry for keeping you waiting!

No problem. 
Ideally I should contribute together, but for time and technical reasons I cannot.😥

Thank you for your great library!

**Comment by qnighy** [comment]
I've published @hi18n/cli@0.1.6 including the following changes: https://github.com/wantedly/hi18n/blob/%40hi18n/cli%400.1.6/packages/cli/CHANGELOG.md

Also see [README](https://github.com/wantedly/hi18n/blob/%40hi18n/cli%400.1.6/packages/cli/README.md).

It will solve the issue you reported. Example:

```javascript
// .hi18nrc.js
module.exports = {
  parser: "@typescript-eslint/parser",
  baseUrl :".",
}
```

**Comment by lightsound** [comment]
Thanks for the fix!

I have checked and found that if I map the catalog directly as shown below, it will not work. If I define them separately, it won't be a problem, but I will report it just in case.

```tsx
const book = new Book<Vocabulary>({
  ja: new Catalog<Vocabulary>({
    // ...
  }),
  en: new Catalog<Vocabulary>({
    // ...
  }),
});
```

**Comment by qnighy** [comment]
> I have checked and found that if I map the catalog directly as shown below, it will not work.

This is explicitly described as non-well-formed in [File Layout](https://github.com/wantedly/hi18n/blob/master/README.md#file-layout).

You can use `@hi18n/eslint-plugin` to check if you are using hi18n in an intended way:

```javascript
// .eslintrc.js
module.exports = {
  extends: ["plugin:@hi18n/recommended"],
};
```

**Comment by qnighy** [comment]
Closing as likely resolved. Please do not overload multiple reports in a single issue next time.
